### PR TITLE
GH-47 Add acceptance test for WebSocket scenarios

### PR DESCRIPTION
**Pull request by ceilfors**
Attempts to close GH-47

### CODE REVIEW

**Comment by ceilfors** [comment]
On the adapter implementation, do you think we should actually inject `body` instead of `ApiGatewayWebSocketEvent` object?

Before
```js
const app = async (message, { wsClient }) => {
  if (message.body.message === "order received") {
    return wsClient.send({ message: "thank you for your order" });
  }
};
```

After
```js
const app = async (message, { wsClient }) => {
  if (message === "order received") {
    return wsClient.send({ message: "thank you for your order" });
  }
};
```

**Comment by Strernd** [comment]
I think it should rather be
```
const app = async ({ message }, { wsClient }) => {
  if (message === "order received") {
    return wsClient.send({ message: "thank you for your order" });
  }
};
```
shouldn't it?

I would like that way, we should put the requestContext with the laconiaContext then.

**Comment by ceilfors** [comment]
Thanks @Strernd. Would you mind reviewing the rest of the acceptance test? I'm not really familiar with WebSocket, just wanted to make sure that everything looks ok and close enough to reality.

**Comment by ceilfors** [comment]
Merging due to inactivity

**Pull request merged**
