### PR TITLE
Laconia#48 - Ignore if callback is falsy

### PR DESCRIPTION
**Pull request by hugosenari**
Partially solves #48 
Changes:

1. Use return when callback is falsy;
2. Introduce a configuration that we eventually deprecate i.e. LACONIA_NO_CALLBACK = true;

Things to do after that (for other PRs):
1. Update documentation with LACONIA_NO_CALLBACK;
2. Add warning for deprecations of callback usage;
3. Rewrite batch to work without callback;
4. Remove anything (configs, warning and callback).

### CODE REVIEW

**Comment by hugosenari** [comment]
I know, I have another branch for @geoffdutton solution and found where is the [fail point](https://github.com/hugosenari/laconia/commit/076187f79c6eac4ad9fd00ea42d2eb75404dcec8), but it [breaks API](/laconiajs/laconia/issues/48#issuecomment-557204483).

Options:
1. Update major version (accept the breaking changes);
  - We need rewrite laconia/batch to use Async/Iterator;
2. Create another entrypoint (ie: @laconia/core/async);
  - Leaves laconia/batch using legancy api.

And is not just warnings, annoys me that I need set context.callbackWaitsForEmptyEventLoop to false because we are using callbacks, thats why I suggest that if we don't have callback, we don't use it. And since it will be a common pattern (unless we break api) create built-in boiler plate to do that.

**Comment by hugosenari** [comment]
Updates:
- Removed: async wrapper
- Introduce a configuration that we eventually deprecate i.e. LACONIA_NO_CALLBACK = true, as @ceilfors  suggested.

**Comment by FrancoMeriles** [comment]
This will come out in the next release ?

**Comment by hugosenari** [comment]
closing this in favor of: #511

**Pull request closed without merging**
