### PR TITLE
Implement async/await listeners for @laconia/batch

### PR DESCRIPTION
**Pull request by ceilfors**
# Context

See https://github.com/laconiajs/laconia/issues/838

# Change

This PR will make @laconia/batch wait for each item to be fully processed when the listener specified is an async function.

# Consideration

There are multiple libraries out in the wild that can replace `EventEmitter` and support async functions. The challenge is to find a library that doesn't break laconia's backward compatibility:

| Library | Pros | Cons |
|-|-|-|
| [emittery](https://www.npmjs.com/package/emittery) | 13mil weekly download | Doesn't support multiple args! |
| [async-eventemitter](https://www.npmjs.com/package/async-eventemitter) | 200k weekly download | Doesn't support multiple args! |
| [await-event-emitter](https://www.npmjs.com/package/await-event-emitter) | Compatible with laconia | 5.5k weekly download |

We actually tried `emittery` before https://github.com/laconiajs/laconia/commit/f8e7e8ff04d1c86f8ddd57a4e193f1ea57fa2ee2. Unfortunately it was reverted as it doesn't support multiple args, this breaks backward compatibility. https://github.com/laconiajs/laconia/commit/9c2b7dcf0389145261d36c48c407fed9d623ade6.

Our only option then is to use `await-event-emitter`. Even though it's not as popular, our comprehensive test suites will make sure that laconia still works.

### CODE REVIEW

**Comment by hugosenari** [comment]
Just checking:
The bug: we are not awaiting all items callback to complete
This PR: we will await item callback to complete and then call another or finish
But could be: we will not wait unless we're finishing, then we have to wait all pending

I'm not sure about this last one, that's the question, 
- Good: I faced cases where PR behavior is desirable
- Bad: Could reduce parallelism of batch process
- Ugly: Await all could add unnecessary(?) complexity and memory leaks

**Comment by ceilfors** [comment]
@hugosenari Hello! I'm glad you're still here!

Thanks for your thoughts.

> Bad: Could reduce parallelism of batch process

When we're hitting an API endpoint via laconia/batch, we have the following scenarios:

| Scenario | Slow endpoint? | Rate limited endpoint? |
|-|-|-|
| 1 | Yes | Yes |
| 2 | Yes | No |
| 3 | No | Yes |
| 4 | No | No |

- Scenario 1: Parallelism is undesirable as if it's already slow, that's putting more pressure to the endpoint
- Scenario 2: I can see the benefit of parallelism here, but why wouldn't dev just do `Promise.all` instead of using laconia/batch?
- Scenario 3: Not affected by async/await
- Scenario 4: Not affected by async/await

> But could be: we will not wait unless we're finishing, then we have to wait all pending

The way I think about this is what's 'intuitive' in devs head. At the moment, I think most devs think that if they put `async` as the `listener`, `laconia` should wait for it i.e. when they write the following code, the most intuitive thing is that laconia will wait for this code. Do you agree with the intuitiveness?

```
.on('item', async (_, item) =>  wait(1500))
```

> Ugly: Await all could add unnecessary(?) complexity and memory leaks

I'm not sure what complexity and memory leaks you meant by this, could you elaborate more?

**Comment by hugosenari** [comment]
> @hugosenari Hello! I'm glad you're still here!

I never stop believing in the right tool for the job, sadly people use hammer to screwup things, so we have to use other tools.

Let me make something clear: I **never** used laconia/batch :sheep: 
My comments are pure theory.

> why wouldn't dev just do Promise.all instead of using laconia/batch?

Because Laconia author is smarter and made a pretty cool interface that would reduce my code complexity also calling my function again before timeouts.

> > The bug: we are not awaiting all items callback to complete
> 
> A different perspective: we are already waiting for all item callback / listener to complete when they're synchronous.
> 

I'm trying to sum the bug we already have before your PR, to make sure we have a common ground =)

> 
> When we're hitting an API endpoint via laconia/batch, we have the following scenarios:

But 'slow endpoint' could be 'slow IO' or 'slow CPU', if slow IO, endpoint may handle more requests.
And  pressure are handled by 'bottleneck' correct?

> The way I think about this is what's 'intuitive' in devs head. At the moment, I think most devs think that if they put `async` as the `listener`, `laconia` should wait for it i.e. when they write the following code, the most intuitive thing is that laconia will wait for this code. Do you agree with the intuitiveness?

From intuition, I'm not the best guy to ask this question. ;-)

It should wait for it, but there are three ways to wait for it:

```js
let tasks = [1, 2, 3].map(Promise.resolve);

// await synchronous
for (let somePromise of tasks) {
   console.log(await somePromise);
}

// await all
for (let someValue of await Promise.all(tasks)) {
  console.log(someValue)
}

// await race
while (tasks.length) {
   const somePromise = Promises.race(works);
   console.log(await somePromise);
   tasks = tasks.filter(p => p != somePromise);
}
```

I'm not sure what others devs would expect, to me best is race, takes the first completed finish theirs job and goes to the next.
The Better Boarding Method Airlines Won't Use  https://www.youtube.com/watch?v=oAHbLRjF0vo

> I'm not sure what complexity and memory leaks you meant by this, could you elaborate more?

Your solution is simple, I'm reading this books

**Comment by ceilfors** [comment]
@hugosenari Thanks for your thoughts! In this scenario, not supporting async is causing quite an unpredictable behaviour (see the original ticket) - so I think we need to fix that regardless.

**Comment by ceilfors** [comment]
I've released this under 1.13.2-alpha0 to test the solution against https://github.com/mpxr/laconia-batch-test. The issue is now fixed.

With @laconia/batch version 1.10.2:

```
START RequestId: c2b40fc0-7a8b-4a1a-8dc7-ae74a4c90206 Version: $LATEST
2022-07-30T05:54:10.031Z c2b40fc0-7a8b-4a1a-8dc7-ae74a4c90206 INFO START
2022-07-30T05:54:10.616Z c2b40fc0-7a8b-4a1a-8dc7-ae74a4c90206 INFO JOKE { name: 'VS Code', '#1': "What is bread's favorite number? Leaven.", '#2': 'Why are pirates called pirates? Because they arrr!' }
2022-07-30T05:54:12.465Z c2b40fc0-7a8b-4a1a-8dc7-ae74a4c90206 INFO JOKE { name: 'Fleet', '#1': 'My boss told me that he was going to fire the person with the worst posture. I have a hunch, it might be me.', '#2': 'I’ll tell you something about German sausages, they’re the wurst' }
2022-07-30T05:54:14.043Z c2b40fc0-7a8b-4a1a-8dc7-ae74a4c90206 INFO END
END RequestId: c2b40fc0-7a8b-4a1a-8dc7-ae74a4c90206
REPORT RequestId: c2b40fc0-7a8b-4a1a-8dc7-ae74a4c90206 Duration: 4018.30 ms Billed Duration: 4019 ms Memory Size: 1024 MB Max Memory Used: 87 MB Init Duration: 691.50 ms
2022-07-30T06:00:50.210Z c2b40fc0-7a8b-4a1a-8dc7-ae74a4c90206 ERROR Unhandled Promise Rejection {"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error:
```

With @laconia/batch version 1.13.2-alpha0:

```
START RequestId: 9076f0af-0aeb-4db3-a2eb-0564557ff4ab Version: $LATEST
2022-07-30T06:11:02.617Z 9076f0af-0aeb-4db3-a2eb-0564557ff4ab INFO START
2022-07-30T06:11:03.019Z 9076f0af-0aeb-4db3-a2eb-0564557ff4ab INFO JOKE { name: 'VS Code', '#1': 'Where do you take someone who has been injured in a Peek-a-boo accident? To the I.C.U.', '#2': 'Don’t interrupt someone working intently on a puzzle. Chances are, you’ll hear some crosswords.' }
2022-07-30T06:11:05.102Z 9076f0af-0aeb-4db3-a2eb-0564557ff4ab INFO JOKE { name: 'Fleet', '#1': 'How do you make a hankie dance? Put a little boogie in it.', '#2': "I was fired from the keyboard factory yesterday. I wasn't putting in enough shifts." }
2022-07-30T06:11:06.900Z 9076f0af-0aeb-4db3-a2eb-0564557ff4ab INFO JOKE { name: 'Eclipse', '#1': 'My cat was just sick on the carpet, I don’t think it’s feline well.', '#2': "I was going to learn how to juggle, but I didn't have the balls." }
2022-07-30T06:11:06.900Z 9076f0af-0aeb-4db3-a2eb-0564557ff4ab INFO END
END RequestId: 9076f0af-0aeb-4db3-a2eb-0564557ff4ab
REPORT RequestId: 9076f0af-0aeb-4db3-a2eb-0564557ff4ab Duration: 4288.69 ms Billed Duration: 4289 ms Memory Size: 1024 MB Max Memory Used: 87 MB Init Duration: 699.89 ms
```

**Pull request merged**
